### ISSUE TITLE
ola achei um problema com o modulo sui magisk 

### ISSUE THREAD

**Issue by baldjmar** [Magisk-Modules-Repo/riru-sui#1]
quando eu baixei é instalei o modulo sui do magisk, reiniciei o android é tentei abrir como configuração mas não da porque diz como configuração parou, por favor resolva isso o mais rapido possivel, meu android é o 8.1.1 go, galaxy j2 core

**Comment by RikkaW** [comment]
1. English, please
2. Provide log if you have problem
3. Create this issue at https://github.com/RikkaApps/Sui
